#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
  path: /
  methods: GET

app_customer_login:
  path: /login
  methods: GET

app_customer_logout:
  path: /logout
  methods: GET

app_chief_login:
  path: /pro/login
  methods: GET

app_chief_logout:
  path: /pro/logout
  methods: GET

