#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# Home --------------------------

app_home:
  path: /
  methods: GET

# Customer --------------------------

app_customer_login:
  path: /login
  methods: GET

app_customer_register:
  path: /register
  methods: GET

app_customer_logout:
  path: /logout
  methods: GET

# Chief --------------------------

app_chief_login:
  path: /pro/login
  methods: GET

app_chief_register:
  path: /pro/register
  methods: GET

app_chief_logout:
  path: /pro/logout
  methods: GET

