#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# Home --------------------------------------------------------

app_home:
  path: /
  methods: GET

# Customer -----------------------------------------------------

app_customer_login:
  path: /login
  methods: GET

app_customer_register:
  path: /register
  methods: GET

app_new_customer:
  path: /register-process
  methods: POST

app_customer_logout:
  path: /logout
  methods: GET

# Chief --------------------------------------------------------

app_chief_list:
  path: /chefs
  methods: GET

app_chief_login:
  path: /pro/login
  methods: GET

app_chief_register:
  path: /pro/register
  methods: GET

app_chief_logout:
  path: /pro/logout
  methods: GET

# Orders -------------------------------------------------------

app_new_order:
  path: /new-order
  methods: POST

app_orders:
  path: /reservations
  methods: GET

app_cart:
  path: /panier
  methods: GET

# Miscellaneous ------------------------------------------------

app_about_us:
  path: /qui-sommes-nous
  methods: GET

app_contact:
  path: /nous-contacter
  methods: GET